### ISSUE TITLE
colorscheme

### ISSUE THREAD

**Issue by beardedsakimonkey** [lacygoill/config#1]
Hi!

this isn't an issue with the repo -- i just didn't know how else to contact you.  I was curious about the colorscheme you're using in this issue https://github.com/junegunn/fzf/issues/1916.  It doesn't appear to be seoul256 like in your current dotfiles.

PS. thanks for creating a really high quality dotfiles repo and publicizing it. i've learned so much from it!

**Comment by lacygoill** [comment]
Sorry for the late response; I unstar and unfollow my repositories, so I was not notified of this issue.

> I was curious about the colorscheme you're using in this issue junegunn/fzf#1916. It doesn't appear to be seoul256 like in your current dotfiles.

In this other issue, I don't think I was using any particular colorscheme, because I started Vim with a minimal vimrc.  I guess it's the default colorscheme.  It may be using the colors from the terminal I was using in the gif, which should have been xterm.  The latter pick up the colors defined [in `~/.Xresources`](https://github.com/lacygoill/config/blob/0fae106a3cc3efd4f4328e94960bfce7304b9ee8/.Xresources#L241-L278).

**Comment by beardedsakimonkey** [comment]
awesome, thanks!
